package interfaces;

import java.io.IOException;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.image.ImageView;

import javafx.scene.input.MouseEvent;

public class AcceuilController {
	@FXML
	private ImageView productbutt;
	@FXML
	private ImageView sell_butt;

	// Event Listener on ImageView[#productbutt].onMouseClicked
	@FXML
	public void gotoproduct(MouseEvent event) throws IOException {
		// TODO Autogenerated
		Parent root = FXMLLoader.load(getClass().getResource("Products.fxml"));
	     
		productbutt.getScene().setRoot(root);
	}
	// Event Listener on ImageView[#sell_butt].onMouseClicked
	@FXML
	public void gotosell(MouseEvent event) throws IOException {
		// TODO Autogenerated
		Parent root = FXMLLoader.load(getClass().getResource("sellPoints.fxml"));
	     
		sell_butt.getScene().setRoot(root);
	}
}
