package interfaces;
import static interfaces.ProductsController.ur;

import static interfaces.ProductsController.p;

import java.io.File;
import java.io.IOException;
import java.net.URL;
import java.util.ResourceBundle;

import javax.naming.Context;
import javax.naming.InitialContext;
import javax.naming.NamingException;

import entities.Product;
import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.fxml.Initializable;
import javafx.scene.Parent;
import javafx.scene.control.Label;
import javafx.scene.image.Image;
import javafx.scene.image.ImageView;

import javafx.scene.input.MouseEvent;
import produitservice.ProduitserRemote;

public class carteprodController implements Initializable {
	@FXML
	private ImageView prodstat_butt;
	@FXML
	private ImageView product_image;
	@FXML
	private Label product_name;
	@FXML
	private Label product_price;
	@FXML
	private Label product_type;

	// Event Listener on ImageView[#prodstat_butt].onMouseClicked
	@FXML
	public void goto_prodstat(MouseEvent event) throws IOException {
		// TODO Autogenerated
		Parent root = FXMLLoader.load(getClass().getResource("Products.fxml"));
	     
		product_image.getScene().setRoot(root);
	}

	@Override
	public void initialize(URL location, ResourceBundle resources) {
		// TODO Auto-generated method stub
		
		Context context;
		FXMLLoader loader = new FXMLLoader(getClass().getResource("Products.fxml"));
		try {
			Parent root=loader.load();
		} catch (IOException e1) {
			// TODO Auto-generated catch block
			e1.printStackTrace();
		}
		ProductsController display=loader.getController();
		String o =display.ur;
		try {
			context = new InitialContext();
			String j2 = "/CRM-ear/CRM-ejb/Produitser!produitservice.ProduitserRemote";
			ProduitserRemote s = (ProduitserRemote) context.lookup(j2);
			System.out.println(o);
			/*Product p =s.findProductbyUrl(o);*/
			Product k= p;
			if(k!=null){
			product_name.setText(k.getName());
			product_type.setText(k.getType());
			product_price.setText(String.valueOf(k.getPrice()));
			
			final String imageURI = new File(ur.replaceAll("/", "\\\\")).toURI().toString();
			final Image img = new Image(imageURI);
			product_image.setImage(img);			
			}
			
			
		} catch (NamingException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
			
	}
}
