package interfaces;

import javafx.fxml.FXML;

import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Alert;
import javafx.scene.control.Button;

import javafx.scene.control.TextField;
import javafx.stage.Stage;
import javafx.scene.control.Alert.AlertType;
import servicefacture.FactureRemote;

import java.io.IOException;

import javax.naming.Context;
import javax.naming.InitialContext;
import javax.naming.NamingException;

import entities.Operator;
import javafx.event.ActionEvent;

public class HomeController {
	@FXML
	private TextField username;
	@FXML
	private TextField pwd;
	@FXML
	private Button login;
	@FXML
	private Button inscri;
	@FXML
	private Button admin;

	// Event Listener on Button[#login].onAction
	@FXML
	public void loginButton(ActionEvent event) throws IOException, NamingException {
		// TODO Autogenerated
		//------------------context-----------------------
		Context context;
		
		context = new InitialContext();
		String j2 = "/CRM-ear/CRM-ejb/Facture!servicefacture.FactureRemote";
		FactureRemote s= (FactureRemote) context.lookup(j2);
		//---------------login--------------------
		if(s.Log(username.getText(), pwd.getText())==null)
		{
			 Alert alert = new Alert(AlertType.INFORMATION);
			   alert.setTitle("Information Dialog");
			   alert.setHeaderText(null);
			   alert.setContentText("Verify your username and input!");
			   alert.showAndWait();
		}
		else{
			Operator o= new Operator();
			o=s.Log(username.getText(), pwd.getText());
			String image = o.getImage();
			int id = o.getIdoperator();
			FXMLLoader loader = new FXMLLoader(getClass().getResource("Login.fxml"));
			Parent root=loader.load();
			LoginController display=loader.getController();
			//display.setclient(c.getId());
			
			//System.out.println(c.getIdoperator());

			 LoginController controller = 
			loader.<LoginController>getController();
			controller.logo(this, id);;
			 
			 login.getScene().setRoot(root);

		}
	}
	// Event Listener on Button[#inscri].onAction
	@FXML
	public void inscriButton(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#admin].onAction
	@FXML
	public void adminButton(ActionEvent event) {
		// TODO Autogenerated
	}
}
