package interfaces;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.fxml.Initializable;
import javafx.scene.Parent;
import javafx.scene.chart.BarChart;
import javafx.scene.chart.CategoryAxis;
import javafx.scene.chart.NumberAxis;
import javafx.scene.chart.XYChart;
import javafx.scene.control.Button;
import javafx.scene.control.Label;

import java.io.File;
import java.io.IOException;
import java.net.URL;
import java.util.ArrayList;
import java.util.List;
import java.util.ResourceBundle;

import javax.naming.Context;
import javax.naming.InitialContext;
import javax.naming.NamingException;

import entities.Product;
import entities.SalesPoints;
import javafx.event.ActionEvent;
import javafx.scene.image.Image;
import javafx.scene.image.ImageView;

import javafx.scene.input.MouseEvent;
import javafx.scene.layout.AnchorPane;
import produitservice.ProduitserRemote;

public class ProductsController implements Initializable {
	@FXML
	private ImageView sellpoints_butt;
	@FXML
	private ImageView gestionprod_butt;
	@FXML
	private ImageView prodstat_butt;
	@FXML
	private ImageView image1;
	@FXML
	private ImageView image2;
	@FXML
	private ImageView image3;
	@FXML
	private ImageView image4;
	@FXML
	private ImageView image5;
	@FXML
	private ImageView image6;
	@FXML
	private Button prev_page;
	@FXML
	private Button next_page;
	@FXML
	private Button view_p1;
	@FXML
	private Button view_p2;
	@FXML
	private Button view_p3;
	@FXML
	private Button view_p4;
	@FXML
	private Button view_p5;
	@FXML
	private Button view_p6;

    @FXML
    private Label imgurl1;

    @FXML
    private Label imgurl5;

    @FXML
    private Label imgurl4;

    @FXML
    private Label imgurl3;

    @FXML
    private Label imgurl2;

    @FXML
    private Label imgurl6;

	@FXML
    private NumberAxis y;
    @FXML
    private CategoryAxis x;

	int currentpage;
	public static String ur; 
	public static Product p=new Product();


	// Event Listener on ImageView[#sellpoints_butt].onMouseClicked
	@FXML
	public void gotosellpoints(MouseEvent event) throws IOException {
		// TODO Autogenerated
		Parent root = FXMLLoader.load(getClass().getResource("sellPoints.fxml"));
     
		sellpoints_butt.getScene().setRoot(root);
	}

	// Event Listener on ImageView[#gestionprod_butt].onMouseClicked
	@FXML
	public void gotogestion_prod(MouseEvent event) throws IOException {
		// TODO Autogenerated
		Parent root = FXMLLoader.load(getClass().getResource("GestionSell.fxml"));
	     
		gestionprod_butt.getScene().setRoot(root);
	}

	// Event Listener on ImageView[#prodstat_butt].onMouseClicked
	@FXML
	public void goto_prodstat(MouseEvent event) throws  IOException {
		// TODO Autogenerated
		
		Parent root = FXMLLoader.load(getClass().getResource("stat_product.fxml"));
	     
		prodstat_butt.getScene().setRoot(root);	

            	

}
	

	// Event Listener on Button[#prev_page].onAction
	@FXML
	public void go_prev(ActionEvent event) throws NamingException {
		// TODO Autogenerated
		Context context;
		context = new InitialContext();
		String j2 = "/CRM-ear/CRM-ejb/Produitser!produitservice.ProduitserRemote";
		ProduitserRemote s = (ProduitserRemote) context.lookup(j2);

		List<Product> products = new ArrayList<>();
		products = s.listeproducts();
		int l = products.size();
		int npages = l / 6;
		int restprod = l % 6;
		
		currentpage = currentpage-1;
		if (currentpage == 1) {
		
			if (l > 6) {

				loadImage1(products.get(7).getImage());

			}

			if (l > 7) {
				loadImage2(products.get(8).getImage());
			}

			if (l > 8) {
				loadImage3(products.get(9).getImage());
			}

			if (l > 9) {
				loadImage4(products.get(10).getImage());

			}

			if (l > 10) {
				loadImage5(products.get(11).getImage());
			}

			if (l > 11) {
				loadImage6(products.get(12).getImage());
			}
		}
		if( currentpage == 0){

			if (l > 0) {

				loadImage1(products.get(0).getImage());

			}

			if (l > 1) {
				loadImage2(products.get(1).getImage());
			}

			if (l > 2) {
				loadImage3(products.get(2).getImage());
			}

			if (l > 3) {
				loadImage4(products.get(3).getImage());

			}

			if (l > 4) {
				loadImage5(products.get(4).getImage());
			}

			if (l > 5) {
				loadImage6(products.get(5).getImage());
			}
		}
		
		
	}

	// Event Listener on Button[#next_page].onAction
	@FXML
	public void go_next(ActionEvent event) throws NamingException {
		// TODO Autogenerated
		Context context;
		context = new InitialContext();
		String j2 = "/CRM-ear/CRM-ejb/Produitser!produitservice.ProduitserRemote";
		ProduitserRemote s = (ProduitserRemote) context.lookup(j2);

		List<Product> products = new ArrayList<>();
		products = s.listeproducts();
		int l = products.size();
		int npages = l / 6;
		int restprod = l % 6;

		currentpage = currentpage + 1;

		if (currentpage == 1) {
			Image image = new Image("image/default.png");
			image1.setImage(image);
			image2.setImage(image);
			image3.setImage(image);
			image4.setImage(image);
			image5.setImage(image);
			image6.setImage(image);
			
			if (l > 6) {

				loadImage1(products.get(7).getImage());

			}

			if (l > 7) {
				loadImage2(products.get(8).getImage());
			}

			if (l > 8) {
				loadImage3(products.get(9).getImage());
			}

			if (l > 9) {
				loadImage4(products.get(10).getImage());

			}

			if (l > 10) {
				loadImage5(products.get(11).getImage());
			}

			if (l > 11) {
				loadImage6(products.get(12).getImage());
			}

		}
		if (currentpage == 2) {
			Image image = new Image("image/default.png");
			image1.setImage(image);
			image2.setImage(image);
			image3.setImage(image);
			image4.setImage(image);
			image5.setImage(image);
			image6.setImage(image);
			
			if (l > 12) {

				loadImage1(products.get(15).getImage());

			}

			if (l > 13) {
				loadImage2(products.get(14).getImage());
			}

			if (l > 14) {
				loadImage3(products.get(15).getImage());
			}

			if (l > 15) {
				loadImage4(products.get(16).getImage());

			}

			if (l > 16) {
				loadImage5(products.get(17).getImage());
			}

			if (l > 17) {
				loadImage6(products.get(18).getImage());
			}

		}
		
		
	}

	// Event Listener on Button[#view_p1].onAction
	@FXML
	public void view1(ActionEvent event) throws IOException, NamingException {
		// TODO Autogenerated
		Context context;
		context = new InitialContext();
		String j2 = "/CRM-ear/CRM-ejb/Produitser!produitservice.ProduitserRemote";
		ProduitserRemote s = (ProduitserRemote) context.lookup(j2);
		
		List<Product> products = new ArrayList<>();
		products = s.listeproducts();
		if (currentpage ==0){
			p= products.get(0);
			
		}
		if (currentpage ==1){
			p= products.get(6);
			
		}
		if (currentpage ==2){
			p= products.get(12);
			
		}
		
		
		
		
		
		ur=imgurl1.getText().replaceAll( "\\\\","/");
		System.out.println(ur);
		
		Parent root = FXMLLoader.load(getClass().getResource("carteprod.fxml"));
	     
		view_p1.getScene().setRoot(root);

		
	}

	// Event Listener on Button[#view_p2].onAction
	@FXML
	public void view2(ActionEvent event) throws IOException, NamingException {
		// TODO Autogenerated
		ur=imgurl2.getText().replaceAll( "\\\\","/");
		Context context;
		context = new InitialContext();
		String j2 = "/CRM-ear/CRM-ejb/Produitser!produitservice.ProduitserRemote";
		ProduitserRemote s = (ProduitserRemote) context.lookup(j2);
		
		List<Product> products = new ArrayList<>();
		products = s.listeproducts();
		if (currentpage ==0){
			p= products.get(1);
			
		}
		if (currentpage ==1){
			p= products.get(7);
			
		}
		if (currentpage ==2){
			p= products.get(13);
			
		}
		Parent root = FXMLLoader.load(getClass().getResource("carteprod.fxml"));
	     
		view_p2.getScene().setRoot(root);
	}

	// Event Listener on Button[#view_p3].onAction
	@FXML
	public void view3(ActionEvent event) throws IOException, NamingException {
		// TODO Autogenerated
		ur=imgurl3.getText();
		Context context;
		context = new InitialContext();
		String j2 = "/CRM-ear/CRM-ejb/Produitser!produitservice.ProduitserRemote";
		ProduitserRemote s = (ProduitserRemote) context.lookup(j2);
		
		List<Product> products = new ArrayList<>();
		products = s.listeproducts();
		if (currentpage ==0){
			p= products.get(2);
			
		}
		if (currentpage ==1){
			p= products.get(8);
			
		}
		if (currentpage ==2){
			p= products.get(14);
			
		}
		Parent root = FXMLLoader.load(getClass().getResource("carteprod.fxml"));
	     
		view_p3.getScene().setRoot(root);
	}

	// Event Listener on Button[#view_p4].onAction
	@FXML
	public void view4(ActionEvent event) throws IOException, NamingException {
		// TODO Autogenerated
		ur=imgurl4.getText();
		Context context;
		context = new InitialContext();
		String j2 = "/CRM-ear/CRM-ejb/Produitser!produitservice.ProduitserRemote";
		ProduitserRemote s = (ProduitserRemote) context.lookup(j2);
		
		List<Product> products = new ArrayList<>();
		products = s.listeproducts();
		if (currentpage ==0){
			p= products.get(3);
			
		}
		if (currentpage ==1){
			p= products.get(9);
			
		}
		if (currentpage ==2){
			p= products.get(15);
			
		}
		Parent root = FXMLLoader.load(getClass().getResource("carteprod.fxml"));
	     
		view_p4.getScene().setRoot(root);
		
	}

	// Event Listener on Button[#view_p5].onAction
	@FXML
	public void view5(ActionEvent event) throws IOException, NamingException {
		// TODO Autogenerated
		ur=imgurl5.getText();
		Context context;
		context = new InitialContext();
		String j2 = "/CRM-ear/CRM-ejb/Produitser!produitservice.ProduitserRemote";
		ProduitserRemote s = (ProduitserRemote) context.lookup(j2);
		
		List<Product> products = new ArrayList<>();
		products = s.listeproducts();
		if (currentpage ==0){
			p= products.get(4);
			
		}
		if (currentpage ==1){
			p= products.get(10);
			
		}
		if (currentpage ==2){
			p= products.get(16);
			
		}
		Parent root = FXMLLoader.load(getClass().getResource("carteprod.fxml"));
	     
		view_p5.getScene().setRoot(root);
	}

	// Event Listener on Button[#view_p6].onAction
	@FXML
	public void view6(ActionEvent event) throws IOException, NamingException {
		// TODO Autogenerated
		ur=imgurl6.getText();
		Context context;
		context = new InitialContext();
		String j2 = "/CRM-ear/CRM-ejb/Produitser!produitservice.ProduitserRemote";
		ProduitserRemote s = (ProduitserRemote) context.lookup(j2);
		
		List<Product> products = new ArrayList<>();
		products = s.listeproducts();
		if (currentpage ==0){
			p= products.get(5);
			
		}
		if (currentpage ==1){
			p= products.get(11);
			
		}
		if (currentpage ==2){
			p= products.get(17);
			
		}
		Parent root = FXMLLoader.load(getClass().getResource("carteprod.fxml"));
	     
		view_p6.getScene().setRoot(root);
	}

	public void loadImage1(String url) {
		
		final String imageURI = new File(url.replaceAll("/", "\\\\")).toURI().toString();
		final Image img = new Image(imageURI);
		image1.setImage(img);
		imgurl1.setText( url);
		System.out.println(url);
	}

	public void loadImage2(String url) {
		final String imageURI = new File(url.replaceAll("/", "\\\\")).toURI().toString();
		final Image img = new Image(imageURI);
		image2.setImage(img);
		imgurl2.setText(imageURI);

	}

	public void loadImage3(String url) {
		final String imageURI = new File(url.replaceAll("/", "\\\\")).toURI().toString();
		final Image img = new Image(imageURI);
		image3.setImage(img);
		imgurl3.setText(imageURI);
	}

	public void loadImage4(String url) {
		final String imageURI = new File(url.replaceAll("/", "\\\\")).toURI().toString();
		final Image img = new Image(imageURI);
		image4.setImage(img);
		imgurl4.setText(imageURI);

	}

	public void loadImage5(String url) {
		final String imageURI = new File(url.replaceAll("/", "\\\\")).toURI().toString();
		final Image img = new Image(imageURI);
		image5.setImage(img);
		imgurl5.setText(imageURI);

	}

	public void loadImage6(String url) {
		final String imageURI = new File(url.replaceAll("/", "\\\\")).toURI().toString();
		final Image img = new Image(imageURI);
		image6.setImage(img);
		imgurl6.setText(imageURI);
	}

	@Override
	public void initialize(URL location, ResourceBundle resources) {
		// TODO Auto-generated method stub
		Context context;
		
		imgurl1.setVisible(false);
		imgurl2.setVisible(false);
		imgurl3.setVisible(false);
		imgurl4.setVisible(false);
		imgurl5.setVisible(false);
		imgurl6.setVisible(false);
		 
		
		try {
			context = new InitialContext();
			String j2 = "/CRM-ear/CRM-ejb/Produitser!produitservice.ProduitserRemote";
			ProduitserRemote s = (ProduitserRemote) context.lookup(j2);

			currentpage = 0;
			Image image = new Image("image/default.png");
			image1.setImage(image);
			image2.setImage(image);
			image3.setImage(image);
			image4.setImage(image);
			image5.setImage(image);
			image6.setImage(image);

			List<Product> products = new ArrayList<>();
			products = s.listeproducts();
			int l = products.size();
			int npages = l / 6;
			int restprod = l % 6;

			if (l > 0) {

				loadImage1(products.get(0).getImage());

			}

			if (l > 1) {
				loadImage2(products.get(1).getImage());
			}

			if (l > 2) {
				loadImage3(products.get(2).getImage());
			}

			if (l > 3) {
				loadImage4(products.get(3).getImage());

			}

			if (l > 4) {
				loadImage5(products.get(4).getImage());
			}

			if (l > 5) {
				loadImage6(products.get(5).getImage());
			}

		} catch (NamingException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}

	}
}
