package interfaces;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import javax.naming.Context;
import javax.naming.InitialContext;
import javax.naming.NamingException;

import entities.Product;
import entities.SalesPoints;
import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.image.ImageView;

import javafx.scene.input.MouseEvent;
import produitservice.ProduitserRemote;
import javafx.scene.chart.CategoryAxis;
import javafx.scene.Parent;
import javafx.scene.chart.BarChart;

import javafx.scene.chart.NumberAxis;
import javafx.scene.chart.XYChart;

public class stat_productController {
	@FXML
	private ImageView back_stat;
	@FXML
	private BarChart LineChart;
	@FXML
	private CategoryAxis x;
	@FXML
	private NumberAxis y;
	@FXML
	private ImageView stats;

	// Event Listener on ImageView[#back_stat].onMouseClicked
	@FXML
	public void goto_prod(MouseEvent event) throws IOException {
		// TODO Autogenerated
		Parent root = FXMLLoader.load(getClass().getResource("Products.fxml"));
	     
		back_stat.getScene().setRoot(root);
	}
	// Event Listener on ImageView[#stats].onMouseClicked
	@FXML
	public void start_stat(MouseEvent event) throws NamingException {
		// TODO Autogenerated
		
		Context context;
		context = new InitialContext();
		String j2 = "/CRM-ear/CRM-ejb/Produitser!produitservice.ProduitserRemote";
		ProduitserRemote s = (ProduitserRemote) context.lookup(j2);
		
		List<Product> products = new ArrayList<>();
		products = s.listeproducts();
		
		XYChart.Series<String, Number> f = new XYChart.Series<String, Number>();
		
		for(Product l : s.listeproducts()){
			String b=l.getName();
			int ab =l.getQuantity();
			
			f.getData().add(new XYChart.Data<String,Number>(b,ab));
		}
		LineChart.getData().add(f);
		
		
		
		

}
	}

