package interfaces;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;
import services.AhmedRemote;


import javax.naming.Context;
import javax.naming.InitialContext;
import javax.naming.NamingException;

import entities.Product;
import javafx.event.ActionEvent;

public class testController {
	@FXML
	private Button add;
	@FXML
	private TextField name;
	@FXML
	private TextField price;
	@FXML
	private TextField quantity;
	@FXML
	private TextField type;
	@FXML
	private TextField opid;

	// Event Listener on Button[#add].onAction
	@FXML
	public void addp(ActionEvent event) throws NamingException {
		// TODO Autogenerated
		Product p= new Product();
		
		p.setName(name.getText());
		p.setPrice(Integer.parseInt(price.getText()));
		p.setQuantity(Integer.parseInt(quantity.getText()));
		p.setType(type.getText());
		
		
			Context context =  new InitialContext();
			String jndi = "/CRM-ear/CRM-ejb/Ahmed!services.AhmedRemote";
			AhmedRemote dao = (AhmedRemote) context.lookup(jndi);
		dao.add(p);
		
		
		}
	}

